/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.newapp.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.newapp.Test1;


/**
 * ServiceImpl object for domain model class Test1.
 *
 * @see Test1
 */
@Service("createdb_9.Test1Service")
@Validated
public class Test1ServiceImpl implements Test1Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(Test1ServiceImpl.class);


    @Autowired
    @Qualifier("createdb_9.Test1Dao")
    private WMGenericDao<Test1, byte[]> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Test1, byte[]> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "createdb_9TransactionManager")
    @Override
	public Test1 create(Test1 test1) {
        LOGGER.debug("Creating a new Test1 with information: {}", test1);
        Test1 test1Created = this.wmGenericDao.create(test1);
        return test1Created;
    }

	@Transactional(readOnly = true, value = "createdb_9TransactionManager")
	@Override
	public Test1 getById(byte[] test1Id) throws EntityNotFoundException {
        LOGGER.debug("Finding Test1 by id: {}", test1Id);
        Test1 test1 = this.wmGenericDao.findById(test1Id);
        if (test1 == null){
            LOGGER.debug("No Test1 found with id: {}", test1Id);
            throw new EntityNotFoundException(String.valueOf(test1Id));
        }
        return test1;
    }

    @Transactional(readOnly = true, value = "createdb_9TransactionManager")
	@Override
	public Test1 findById(byte[] test1Id) {
        LOGGER.debug("Finding Test1 by id: {}", test1Id);
        return this.wmGenericDao.findById(test1Id);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "createdb_9TransactionManager")
	@Override
	public Test1 update(Test1 test1) throws EntityNotFoundException {
        LOGGER.debug("Updating Test1 with information: {}", test1);
        this.wmGenericDao.update(test1);

        byte[] test1Id = test1.getName();

        return this.wmGenericDao.findById(test1Id);
    }

    @Transactional(value = "createdb_9TransactionManager")
	@Override
	public Test1 delete(byte[] test1Id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Test1 with id: {}", test1Id);
        Test1 deleted = this.wmGenericDao.findById(test1Id);
        if (deleted == null) {
            LOGGER.debug("No Test1 found with id: {}", test1Id);
            throw new EntityNotFoundException(String.valueOf(test1Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "createdb_9TransactionManager")
	@Override
	public Page<Test1> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Test1s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "createdb_9TransactionManager")
    @Override
    public Page<Test1> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Test1s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "createdb_9TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service createdb_9 for table Test1 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "createdb_9TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "createdb_9TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

